export enum API_TAGS {
  APPLICATIONS = 'APPLICATIONS',
  ADMIN = 'ADMIN',
  AUTH = 'AUTH',
  INTERVIEWS = 'INTERVIEWS',
  JOBS = 'JOBS',
  UPLOADS = 'UPLOADS',
  REPORTS = 'REPORTS',
  REVIEWS = 'REVIEWS',
  SSE = 'SSE',
  APP = 'APP',
  USERS = 'USERS',
}
